  server:
    port: 8080

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enable: true
    endpoints:
      web:
        exposure:
          include: gateway


  spring:
    application:
      name: gateway-service
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
          - id: service-club-id
            uri: lb://club-service
            predicates:
              - Path=/clubs/**
            filters:
              - StripPrefix=1

