eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enable: true
  endpoints:
    web:
      exposure:
        include: gateway
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters: TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
#            allowedOrigins: "https://www.javarubberduck.com"
#            allowedHeaders:
#              - content-type
#            allowedMethods:
#              - GET
#              - POST
#              - DELETE
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          lower-case-service-id: true
      routes:
#        -   id: service-club-id
#            predicates:
#              - Path=/api/v1/**
#            uri: lb://club-service
        - id: service-club-id
          uri: lb://club-service
          predicates:
            - Path=/clubs/**
          filters:
            - StripPrefix=1
  security:
    basic:
      enable: false
    ignored: /**
